### ISSUE TITLE
Will not import in python script on raspberry pi

### ISSUE THREAD

**Issue by justcallmekoko** [adafruit/Adafruit_CircuitPython_Touchscreen#12]
I installed this library on my raspberry pi zero w by following the instructions on the README which dictate I use pip3.

I imported the library in my script in the same way shown in the example but I receive the following error...

```python
Traceback (most recent call last):
  File "touch_import.py", line 2, in <module>
    import adafruit_touchscreen
  File "/usr/local/lib/python3.7/dist-packages/adafruit_touchscreen.py", line 47, in <module>
    from analogio import AnalogIn
  File "/usr/local/lib/python3.7/dist-packages/analogio.py", line 21, in <module>
    raise NotImplementedError("analogio not supported for this board.")
NotImplementedError: analogio not supported for this board.
```

**Comment by ladyada** [comment]
correct, there are no analog inputs on a raspberry pi, you can use an stmpe610/stmpe811 to do the analog reads
https://www.adafruit.com/product/1571
